[2025-02-08T13:02:39.083+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: pipeline_milestone_3.post_to_elasticsearch manual__2025-02-08T13:02:18.930461+00:00 [queued]>
[2025-02-08T13:02:39.092+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: pipeline_milestone_3.post_to_elasticsearch manual__2025-02-08T13:02:18.930461+00:00 [queued]>
[2025-02-08T13:02:39.092+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-02-08T13:02:39.092+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2025-02-08T13:02:39.092+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-02-08T13:02:39.102+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): post_to_elasticsearch> on 2025-02-08 13:02:18.930461+00:00
[2025-02-08T13:02:39.110+0000] {standard_task_runner.py:52} INFO - Started process 393 to run task
[2025-02-08T13:02:39.114+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'pipeline_milestone_3', 'post_to_elasticsearch', 'manual__2025-02-08T13:02:18.930461+00:00', '--job-id', '133', '--raw', '--subdir', 'DAGS_FOLDER/P2M3_RizkySP_DAG.py', '--cfg-path', '/tmp/tmpj7wx1f9_', '--error-file', '/tmp/tmpu5jjlgvg']
[2025-02-08T13:02:39.115+0000] {standard_task_runner.py:80} INFO - Job 133: Subtask post_to_elasticsearch
[2025-02-08T13:02:39.167+0000] {task_command.py:371} INFO - Running <TaskInstance: pipeline_milestone_3.post_to_elasticsearch manual__2025-02-08T13:02:18.930461+00:00 [running]> on host b33620135048
[2025-02-08T13:02:39.207+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=RizkySP
AIRFLOW_CTX_DAG_ID=pipeline_milestone_3
AIRFLOW_CTX_TASK_ID=post_to_elasticsearch
AIRFLOW_CTX_EXECUTION_DATE=2025-02-08T13:02:18.930461+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-02-08T13:02:18.930461+00:00
[2025-02-08T13:02:39.233+0000] {base.py:271} INFO - HEAD http://elasticsearch:9200/ [status:200 request:0.024s]
[2025-02-08T13:02:39.233+0000] {logging_mixin.py:115} INFO - Connected to Elasticsearch
[2025-02-08T13:02:39.243+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/P2M3_RizkySP_DAG.py", line 61, in post_to_elasticsearch
    data_clean = pd.read_csv(data_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 614, in get_handle
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 396, in _get_filepath_or_buffer
    raise ValueError(msg)
ValueError: Invalid file path or buffer object type: <class 'NoneType'>
[2025-02-08T13:02:39.253+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=pipeline_milestone_3, task_id=post_to_elasticsearch, execution_date=20250208T130218, start_date=20250208T130239, end_date=20250208T130239
[2025-02-08T13:02:39.257+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 133 for task post_to_elasticsearch (Invalid file path or buffer object type: <class 'NoneType'>; 393)
[2025-02-08T13:02:39.296+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2025-02-08T13:02:39.313+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
