[2025-02-08T13:01:39.401+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: pipeline_milestone_3.post_to_elasticsearch manual__2025-02-08T13:01:29.655265+00:00 [queued]>
[2025-02-08T13:01:39.414+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: pipeline_milestone_3.post_to_elasticsearch manual__2025-02-08T13:01:29.655265+00:00 [queued]>
[2025-02-08T13:01:39.414+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-02-08T13:01:39.414+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2025-02-08T13:01:39.414+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-02-08T13:01:39.423+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): post_to_elasticsearch> on 2025-02-08 13:01:29.655265+00:00
[2025-02-08T13:01:39.433+0000] {standard_task_runner.py:52} INFO - Started process 354 to run task
[2025-02-08T13:01:39.436+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'pipeline_milestone_3', 'post_to_elasticsearch', 'manual__2025-02-08T13:01:29.655265+00:00', '--job-id', '130', '--raw', '--subdir', 'DAGS_FOLDER/P2M3_RizkySP_DAG.py', '--cfg-path', '/tmp/tmpc491c_y_', '--error-file', '/tmp/tmp8au1oq27']
[2025-02-08T13:01:39.438+0000] {standard_task_runner.py:80} INFO - Job 130: Subtask post_to_elasticsearch
[2025-02-08T13:01:39.498+0000] {task_command.py:371} INFO - Running <TaskInstance: pipeline_milestone_3.post_to_elasticsearch manual__2025-02-08T13:01:29.655265+00:00 [running]> on host b33620135048
[2025-02-08T13:01:39.559+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=RizkySP
AIRFLOW_CTX_DAG_ID=pipeline_milestone_3
AIRFLOW_CTX_TASK_ID=post_to_elasticsearch
AIRFLOW_CTX_EXECUTION_DATE=2025-02-08T13:01:29.655265+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-02-08T13:01:29.655265+00:00
[2025-02-08T13:01:39.599+0000] {base.py:271} INFO - HEAD http://elasticsearch:9200/ [status:200 request:0.035s]
[2025-02-08T13:01:39.599+0000] {logging_mixin.py:115} INFO - Connected to Elasticsearch
[2025-02-08T13:01:41.477+0000] {base.py:299} WARNING - POST http://elasticsearch:9200/milestone3_clean/_bulk [status:400 request:0.567s]
[2025-02-08T13:01:41.505+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/P2M3_RizkySP_DAG.py", line 69, in post_to_elasticsearch
    es.bulk(index=index_name, body=[{"index": {}}] + data_dict)
  File "/home/airflow/.local/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 168, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/elasticsearch/client/__init__.py", line 468, in bulk
    body=body,
  File "/home/airflow/.local/lib/python3.7/site-packages/elasticsearch/transport.py", line 415, in perform_request
    raise e
  File "/home/airflow/.local/lib/python3.7/site-packages/elasticsearch/transport.py", line 388, in perform_request
    timeout=timeout,
  File "/home/airflow/.local/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 277, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/airflow/.local/lib/python3.7/site-packages/elasticsearch/connection/base.py", line 331, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.RequestError: RequestError(400, 'illegal_argument_exception', 'Malformed action/metadata line [3], expected START_OBJECT or END_OBJECT but found [VALUE_STRING]')
[2025-02-08T13:01:41.669+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=pipeline_milestone_3, task_id=post_to_elasticsearch, execution_date=20250208T130129, start_date=20250208T130139, end_date=20250208T130141
[2025-02-08T13:01:41.889+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 130 for task post_to_elasticsearch (RequestError(400, 'illegal_argument_exception', 'Malformed action/metadata line [3], expected START_OBJECT or END_OBJECT but found [VALUE_STRING]'); 354)
[2025-02-08T13:01:41.949+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2025-02-08T13:01:42.015+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
